apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-netmanager
  namespace: oakestra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster
  template:
    metadata:
      labels:
        app: cluster
    spec:  
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: plugin
                operator: In
                values:
                - oakestra
            topologyKey: kubernetes.io/hostname
      containers:
      - name: cluster-service-manager
        image: ghcr.io/jakobke/oakestra-cluster-service-manager:0.2-amd
        imagePullPolicy: Always
        ports:
        - containerPort: 10110
        env:
        - name: MY_PORT
          value: "10110"
        - name: MQTT_BROKER_PORT
          value: "10003"
        - name: MQTT_BROKER_URL
          value: "10.106.240.155"
        - name: ROOT_SERVICE_MANAGER_URL
          value: "10.100.253.175"
        - name: ROOT_SERVICE_MANAGER_PORT
          value: "10099"
        - name: SYSTEM_MANAGER_URL
          value: "10.100.253.175"
        - name: SYSTEM_MANAGER_PORT
          value: "10000"
        - name: CLUSTER_MONGO_URL
          value: "10.106.233.73" 
        - name: CLUSTER_MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-service-manager-svc
  namespace: oakestra-system
spec:
  type: NodePort
  selector:
    app: cluster
  ports:
  - protocol: TCP
    port: 10110
    targetPort: 10110
    nodePort: 30330 

