apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: oakestra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
      - name: configsetup
        volumeMounts:
        - mountPath: /mosquitto/config/
          name: config
        - mountPath: /mosquitto/config-init/
          name: init-config
        image: alpine
        command: 
        - cp 
        - /mosquitto/config-init/mosquitto.conf
        - /mosquitto/config/mosquitto.conf
        
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6
        ports:
        - containerPort: 10003
        volumeMounts:
        - mountPath: /mosquitto/config/
          name: config
        - mountPath: /mosquitto/data/
          name: data
      volumes:
      - name: init-config
        configMap:
          name: mosquitto-config
      - name: data
        persistentVolumeClaim:
          claimName: mosquitto-data
      - name: config
        emptyDir: {}



---


apiVersion: v1
kind: Service
metadata:
  name: mosquitto-svc
  namespace: oakestra-system
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
  - protocol: TCP
    port: 10003
    targetPort: 10003
    nodePort: 30033

--- 


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: oakestra-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: mosquitto-pv


---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
  namespace: oakestra-system
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data-oakestra/mosquitto"