# permissions for end users to edit OakestraJobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: OakestraJob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oakestra-OakestraJob-operator
    app.kubernetes.io/part-of: oakestra-OakestraJob-operator
    app.kubernetes.io/managed-by: kustomize
  name: OakestraJob-editor-role
rules:
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - OakestraJobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - OakestraJobs/status
  verbs:
  - get
