---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - oakestrajobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - oakestrajobs/finalizers
  verbs:
  - update
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - oakestrajobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - oakestra.oakestra.kubernetes
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
