apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: oakestra.kubernetes.network
  objectSelector:
    matchLabels:
      oakestra.io/network: active
  patches:
  - op: add
    path: /webhooks/0/objectSelector
    value:
      matchLabels:
        oakestra.io/network: active