apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: oakestra-controller-manager
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: oakestra-controller-manager
  name: configmap-reader-binding
subjects:
- kind: ServiceAccount
  name: webhook-service-account
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io